version: '2'
services:
  junction-app:
    image: junction
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://junction-mysql:3306/junction?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_CACHE_REDIS_SERVER=redis://junction-redis:6379
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  junction-mysql:
    extends:
      file: mysql.yml
      service: junction-mysql
  junction-redis:
    extends:
      file: redis.yml
      service: junction-redis
